### ISSUE TITLE
AWSCognitoAuth SignIn error=Loading page failed

### ISSUE THREAD

**Issue by ksenia834** [aws/aws-sdk-ios#1003]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWSCognitoAuth with SAML Identity Provider (Azure AD)

* In what version of SDK are you facing the problem?
AWSCognitoAuth        - v.2.6.25
AWSUserPoolsSignIn - v.2.6.25
AWSAuthCore             - v.2.6.25

* Is the issue limited to Simulators / Actual Devices?
Issue is reproducing on iOS Simulator and Actual Device

* Can your problem be resolved if you bump to a higher version of SDK?
This is already the latest release version of AWS and iOS SDKs

* Is this problem related to specific iOS version?
Issue is reproducing on iPhone 7 with iOS 11.3.1, iPad Pro iOS 11.4.1. 
I can't reproduce it on iPad with iOS 10.3.1, so not sure about version dependency.

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
With Cocoapods

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

Steps to reproduce:
1. Login user with Azure AD account.
2. Logout user.
3. Wait few seconds: 0 - 60.
4. Login again.

Actual result: Error Domain=com.amazon.cognito.AWSCognitoAuthErrorDomain Code=-2000 "(null)" UserInfo={error=Loading page failed}.
Expected result: Show SignIn Screen to the user.

Additional information:
AWSCognitoAuth methods used for sign-in:

first variant:
– getSession:completion:
– signOut:completion:

second variant:
– getSession:
– signOut:

Issue is regardless of which variant is used.

Issue is also reproducing on example project: https://github.com/awslabs/aws-sdk-ios-samples/tree/master/CognitoAuth-Sample/Objective-C/CognitoAuthSample with required AWS settings.

I also found that similar issue was already opened and closed without solving an error: 
https://github.com/aws/aws-sdk-ios/issues/857

Do you have any information what the reason of this problem and is it possible to solve this error on AWS SDK side?

Thanks!

**Comment by moisesrojasGL** [comment]
Hi @ksenia834 any luck on this? I have the same issue.

**Comment by moisesrojasGL** [comment]
Hi @ksenia834 I think the best solution is to implement `ASWebAuthenticationSession` in some sort of Swift Extension (or in a fork/branch from this SDK) since this is the right way to load web pages to handle one-time login (at least when using Google Sign-in, my case). I hope this be fixed by the AWS guys soon. Please see [this](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession) and [this](https://ajkueterman.com/apple/wwdc/sfauthenticationsession-and-aswebauthenticationsession/).

PD: To any of the new visitors on this thread correct me if I'm lost or wrong. Any feedback or update will be appreciated. Thanks!

**Comment by dluquedavid** [comment]
I have the same problem only in iOS 10.
