### ISSUE TITLE
CloudFront  TransferManager

### ISSUE THREAD

**Issue by georgepoenaru** [aws/aws-sdk-ios#135]
We have S3TransferManager but since a lot of applications need it's content in different edge points this option would be very useful. Sure, we can make HTTP requests based on S3 policy but is not so elegant.

**Comment by fmalekpour** [comment]
+1 and specially for upload to CloudFront, addition would be very useful.

**Comment by yosuke-matsuda** [comment]
There are a few aspects to this topic.

If you are looking to download publicly readable contents from Amazon CloudFront, you can use `NSURLSession` to download them.

If you want to generate signed URLs for private content distribution, you should generate the URLs on your server, and your iOS app should retrieve the data from CloudFront using `NSURLSession`.

You should not generate a signed URL on your mobile device because currently there is no secure way to generate a signed URL on mobile device. Amazon CloudFront has a dedicated [forum](https://forums.aws.amazon.com/forum.jspa?forumID=46). You should share your interest is this feature if you are looking for this feature.

If you are using Amazon S3 as your data source for CloudFront, you can use `AWSTransferManager` upload data to the bucket.

Hope it helps,

**Comment by georgepoenaru** [comment]
Is there any difference in uploading data directly into a s3 bucket from a Europe based client into a US based s3 bucket and uploading via an Cloudfront edge ? Does it only forward the POST request to an S3 bucket or it also buffer upload via an edge ? If doesn't make any difference what's the point of POST operations in CloudFront ?

**Comment by yosuke-matsuda** [comment]
The PUT/POST/DELETE support of Amazon CloudFront with Amazon S3 is currently sporadic. There are a number of technical hurdles that need to be overcome on the service side in order to support the mobile use case securely, including:
https://forums.aws.amazon.com/message.jspa?messageID=496076
https://forums.aws.amazon.com/thread.jspa?threadID=167234
https://forums.aws.amazon.com/thread.jspa?messageID=345913

When these issues are resolved, we consider adding it to our SDK. We will work with the CloutFront team; however, we do not have any timeline we can share regarding this feature. Thanks.

**Comment by abhishek-fusioni** [comment]
is it safe now to generate signed URLs for private content distribution at mobile end? or is it still better to generate the URLs on server, and iOS app should retrieve the data from CloudFront?
