### ISSUE TITLE
AWSS3TransferManagerUploadRequest body requires extension

### ISSUE THREAD

**Issue by ryanjm** [aws/aws-sdk-ios#137]
Right now the `AWSS3TransferManagerUploadRequest` requires that the `body` URL include the file extension. If it is left off (that is, if the original file doesn't have one) you get:

```
CFURLResourceIsReachable failed because it was passed this URL which has no scheme: /var/mobile/Containers/Data/Application/C4AD143D-FBEC-4DCB-8239-995174B04BF9/Documents/AppFiles/01389FF6-6064-4137-B46E-74B6DDAFA6BA
```

This worked with v1 since I was able to pass the `NSData` of that file.

I think it should warn _why_ it is failing and potentially try to use the `contentType` to figure out what type of file it is.

**Comment by yosuke-matsuda** [comment]
Without the extension, your file URL is invalid. `CFURLResourceIsReachable failed because it was passed this URL which has no scheme` is an appropriate error message. Automatic content type detection does not always work, so current behavior seems reasonable. Thanks.

**Comment by ryanjm** [comment]
Is there any way to just provide it the data to work with rather than passing it a URL?

**Comment by zee-pk** [comment]
I'm also having same issue, it is not related to file extension. 
CFURLResourceIsReachable failed because it was passed this URL which has no scheme: /Users/zee/Library/Developer/CoreSimulator/Devices/F1909140-35DC-47DE-89CD-1D4C7EBEF434/data/Containers/Data/Application/F0176ACA-72ED-4695-BE8D-7E1799643850/Documents/20150715-1322-CCA5AA85-3854-4204-972D-104288E9CE9A.zip
