### ISSUE TITLE
Cocoapods 0.36.0.beta.2 not working

### ISSUE THREAD

**Issue by bpudenz** [aws/aws-sdk-ios#145]
An empty project with "pod 'AWSiOSSDKv2'" installed will not run.  Basic AppDelegate AWSServiceManager setup is unrecognized.  I'm guessing it has something to do with the Module mapping.

**Comment by yosuke-matsuda** [comment]
Please use the latest non-beta version of CocoaPods. Currently, 0.35.0 is the latest version. Thanks.

**Comment by szehnder** [comment]
With respect, if you're working on a fix for this in preparation for the 0.36 release of cocoapods, then it would help to know that.  If you're not expecting you'll have to change anything and there's a cocoapods fix in the works, then it'd be great to have reference to that issue in the cocoapods repo.  Otherwise your answer is rather unhelpful to those of us trying to be good stewards to your library.
