### ISSUE TITLE
Mobile Analytics Session Lengths

### ISSUE THREAD

**Issue by cthomaschase** [aws/aws-sdk-ios#198]
Note: This might (not sure yet) be related to Issue https://github.com/aws/aws-sdk-ios/issues/197

Here is a sample set from Redshift:

![cthomaschase_ _psql_ _247x70](https://cloud.githubusercontent.com/assets/455635/8025256/b58ed530-0d03-11e5-904b-168766386a6d.png)

As you can see, we have absurdly long sessions occurring. Unless I'm missing something with regards to how AWSMA classifies a session, I find it hard to believe a session could span multiple days.

*Note - We have the same behavior in our Android implementation as well.*

Anyone else seeing this?

**Comment by yyzhu** [comment]
Thanks for the screenshot. I believe it is the same issue of #197 , please refer to answer of that issue.

**Comment by cthomaschase** [comment]
@yyzhu the explanation of the issue with clock skew makes sense for https://github.com/aws/aws-sdk-ios/issues/197, but not really for this one. The timestamps seem *good*, yet the span of the session seems off. You were able to reproduce this as well?

**Comment by yyzhu** [comment]
Let me try to explain this (the line pointed by red arrow): 
First, the client's clock is incorrect. when the app launched, session_start_timestamp has been recorded using incorrect date (2015-05-05), then a couple of seconds later, then first event has been recorded with the incorrect date again (2015-05-05). At this time, the event has been submitted to server, and the SDK were able to correct the date by using the response package from AMA server, therefore app's date has been corrected to 2015-05-15. Last, the client leave the app, the session _stop_timestamp has been recorded by using app's corrected date ( 2015-05-15). 

Again, this inconsistence has been fixed in latest SDK, which means clockskew will not kicked-in for all AMA events, in this case, the session_stop_teimstamp will use client's system date :2015-05-05.

**Comment by cthomaschase** [comment]
@yyzhu great thanks, that makes sense.

**Comment by fosterzhang** [comment]
@cthomaschase do you have a screenshot for Android? The Android SDK is a little different. You have to manage the session yourself. If stopSession()/resumeSession() isn't called properly, it'll result in funky session. Please open an issue in the Android SDK repo if necessary.
