### ISSUE TITLE
AWSTask returning result null

### ISSUE THREAD

**Issue by sebaro1989** [aws/aws-sdk-ios#262]
I have been trying to upgrade from version 1 to the new sdk, but every time I try to upload an image the:

 AWSS3TransferManager *transferManager = [AWSS3TransferManager defaultS3TransferManager];
    [[transferManager upload:uploadRequest] continueWithBlock:^id(AWSTask *task) { 

The transfer manager returns almost instantly and the result is always the same:

AWSTask: 0x17446a4c0; completed = YES; cancelled = NO; faulted = NO; result:(null)

And the image does not get uploaded.
I have tried out this code in other projects and it works perfectly, somebody has been through this issue?

(I have also tried using transfer utility and the results were basically the same)
Thanks in advance!

**Comment by fosterzhang** [comment]
An AWSTask object represents the result of an asynchronous method. Using AWSTask, you can wait for an asynchronous method to return a value, and then do something with that value after it has returned. You can chain async requests instead of nesting them. This helps keep logic clean and code readable.

For more details, see our developer guide about AWSTask http://docs.aws.amazon.com/mobile/sdkforios/developerguide/awstask.html.

**Comment by sebaro1989** [comment]
Thanks for your quick reply! 

But im checking inside the block and the request is marked as completed, but the data has not been uploaded, is this coherent? 

I´m not getting any error, I also checked the upload progress using the transfer utility and the upload seems to get restarted halfway but never gets fully uploaded.

**Comment by yosuke-matsuda** [comment]
Do you see the same issue with this [sample app](https://github.com/awslabs/aws-sdk-ios-samples/tree/master/S3TransferManager-Sample)? In which region is your bucket located? Have you made sure you set the correct region for your bucket?

**Comment by yosuke-matsuda** [comment]
I assume the issue has been resolved. Please feel free to update the thread if you continue encountering the issue. Thanks.
