### ISSUE TITLE
Nil detection for S3TransferUtilityForKey in Swift is a bit weird

### ISSUE THREAD

**Issue by robbiet480** [aws/aws-sdk-ios#330]
I need to determine if an S3TransferUtility has been previously created. I eventually figured out that I can do it this way:
```swift
let existingTransferUtility = AWSS3TransferUtility.S3TransferUtilityForKey(utilityKey)

if existingTransferUtility != existingTransferUtility {
    let credentialsProvider = AWSStaticCredentialsProvider(accessKey: awsAccessKeyID, secretKey: awsSecretAccessKey)
    let configuration = AWSServiceConfiguration(region: getRegionForString(awsRegion), credentialsProvider: credentialsProvider)
    AWSS3TransferUtility.registerS3TransferUtilityWithConfiguration(configuration, forKey: utilityKey)
}
```

but the if conditional seems like pretty awkward syntax. I think that the best implementation would be something like this:

```swift
if AWSS3TransferUtility.S3TransferUtilityForKey(utilityKey) == nil {
  print("No existing transfer utility with that key!")
}
```

Using this suggested syntax currently returns this error: `Initializer for conditional binding must have Optional type, not 'AWSS3TransferUtility'`.

**Comment by yosuke-matsuda** [comment]
In general, you should use `dispatch_once()` to make sure `+ registerS3TransferUtilityWithConfiguration:forKey:` is called only once. (`+ S3TransferUtilityForKey` never returns `nil`.) If there is something that prevents from you to adopt the pattern, could you describe your use case in details so that we can understand your requirements? Thanks.

**Comment by robbiet480** [comment]
@yosuke-matsuda I (potentially) need to create multiple S3TransferUtility with different configurations for each so I don't believe `dispatch_once()` will work for my specific case.

The reason I am expecting `nil` from `S3TransferUtilityForKey` is because the [documentation](http://docs.aws.amazon.com/AWSiOSSDK/latest/Classes/AWSS3TransferUtility.html#//api/name/S3TransferUtilityForKey:) says it will return `nil` 
> if + registerS3TransferUtilityWithConfiguration:forKey: has not been called in advance or the key does not exist

**Comment by yosuke-matsuda** [comment]
The documentation is outdated. It's not defined as `nullable`. We'll update the API doc. Also, please describe your use case in more details. Thanks.

**Comment by robbiet480** [comment]
I am building an application which allows users to automatically upload data to S3 buckets owned by their AWS accounts which means that they have to input credentials to use for uploading. The user can have multiple upload jobs configured at the same time and they will always fire in the background. I need to create an S3TransferUtility for every upload job, because each upload job may have different credentials.

**Comment by yosuke-matsuda** [comment]
I see, it is a management console like application use case. We recommend keeping track of what configurations have been created in your application and calling the register method accordingly. Your first code snippet is syntactically not correct although it may work fine now. (`existingTransferUtility` should never be `nil`.) It may stop working in the future.

Defining the return type of  `+ S3TransferUtilityForKey:` to `nonnull` makes it easier for many developers to use the class because they do not have to add an additional `let` to unwrap the optional. So, changing this method signature may not be the best path we can take.

**Comment by yosuke-matsuda** [comment]
We've fixed the documentation issue. Thanks.

**Comment by robbiet480** [comment]
@yosuke-matsuda Thanks so much for updating the documentation!
