### ISSUE TITLE
Separate code dependencies by using a package manager

### ISSUE THREAD

**Issue by samdmarshall** [aws/aws-sdk-ios#335]
I am going through the SDK and finding a LOT of third party code (based on the various licenses) that has been re-prefixed and added to these libraries. To better understand what should and shouldn't be interacted with from the SDK side, can you please separate these out from your own shipped code or at least structure the projects in such a way it makes it clear what code is Amazon's and which is from a third party?

Filing bugs on these frameworks is (currently) a lot more work that it should be because of this additional overhead of separating if the code needs to be addressed by a third party as well. Since you provide installation via CocoaPods, it seems reasonable to say that your podspec should be defining all the third party dependencies it needs. This would reduce a great number of duplicated code dependencies I am experiencing because you are using much of the same third party libraries that I am already using in my app.

Thanks.

**Comment by yosuke-matsuda** [comment]
The dependency manager is not always capable of resolving the dependencies (such as when there is conflicting dependencies). Also, we distribute our SDK not only through CocoaPods but as compiled frameworks as well. I understand there can be some duplicated code, but we believe shipping these prefixed third-party libraries simplifies the integration steps, especially for novice developers. We currently do not have plans to define dependencies in podspecs. Thanks.

**Comment by samdmarshall** [comment]
Thanks for the response! I'm sorry, but I'm having a little trouble understanding the statement you made about this issue. 

My understanding is that the dependency resolver that CocoaPods uses is responsible for resolving conflicts automatically. If there is an issue that it cannot resolve itself through transitive dependencies, then that speaks to a much greater issue of the overall architecture of the code. While it is true that could pose a challenge to a novice developer as you said, I don't understand why you would limit the architecture and integration of everyone else on such a factor. 

Additionally, I don't understand how shipping a podspec that enumerates your actual code dependencies remotely impacts you being able to ship a binary version of this library. I could understand if the team maintaining the AWS iOS SDK is not in a position to make this change, but i find it troubling that you are justifying not making this change based on largely irrelevant information.

If you aren't willing or able to make this change, then I can accept that and you can go ahead to close this issue. Thanks again.

**Comment by yosuke-matsuda** [comment]
Here is a simple example of the situation where the dependency management cannot resolve the dependencies.
- AWS SDK depends on LibraryA version 2.3.x.
- LibraryB depends on LibraryA version 1.2.x.

If a developer wants to use the AWS SDK and LibraryB in their project, they simply cannot because of the conflicting dependencies. By prefixing them and including our dependencies in our SDK, the developer does not have to worry about any kinds of conflict.

Also, we sometimes make small changes to the third-party libraries to improve the developer integration steps. For example, some third-party libraries require `-ObjC` Linker Flag to be added to the project; however, our SDK does not require the flag because of the changes we make to the libraries.

Overall, we believe including all of our dependencies in our SDK provides better developer experience.

**Comment by samdmarshall** [comment]
I think this disagreement comes from a fundamental difference in stance as to what the expectation of the library maintainer is. While making your API convenient to consume is most certainly a bonus for creating a new community, in my mind it isn't the job of the library author to construct the API in such a way that it becomes unwieldily to integrate into existing systems. I think that it is a pretty large assumption that none of the third party code that is included in this library could potentially cause a conflict by being used again by another developer. That is a massive risk to push onto the developer that you want to consume this API. This isn't counting any of the changes to the third party libraries that may have had explicit reason to rely on some of the compiler and linker flags that are specified as part of their integrations.

Overall this reads to me as a maintainer being out of touch with the realities of iOS app development. As I said I do respect your position on this but at the same time your position makes it fundamentally hard for me to justify wanting to explore this as an option given the amount of overhead that it is proving to be. 

I understand that what I am asking here is a non-trivial amount of work to undertake -- and since your entire source code is here on github -- I don't think it is unreasonable for an outside party to comment on the fact that it would be of more of an adoption benefit to seriously consider using a dependency manager for all the dependencies you actually use in this set of frameworks. Please, believe me when I say that I am more familiar with the build system and integration processes for iOS than almost anyone, doing this is going to make your job as a maintainer much easier and greatly simplify the work required to use this SDK.

**Comment by yosuke-matsuda** [comment]
If you look at this repository's history, you can see that when we originally released the version 2 of the AWS Mobile SDK for iOS, we defined all of our dependencies in our podspec.

Over time, we've seen many developers struggled in various stages of the integration steps, and we decided to merge all of the dependencies in our core framework. Since then, we've seen drastically fewer developers struggling to integrate the SDK into their project.

Closing this thread since you seem to be fine with it.
