### ISSUE TITLE
confirmation status flow is not complete?

### ISSUE THREAD

**Issue by nuinisk** [aws/aws-sdk-ios#380]
Hi

when i want to signin with user which is already signup, but not confirmed, i get error

[Debug] AWSURLResponseSerialization.m line:63 | -[AWSJSONResponseSerializer responseObjectForResponse:originalRequest:currentRequest:data:error:] | Response body:
{"__type":"NotAuthorizedException","message":"Incorrect username or password."}

So just imagine the case when i signup user with one device but not confirm, then i want to use same user in another device, so when i try to signin with AWSCognitoIdentityUser getSession i got above mentioned error. 

So will be good to have valid session back with status that user not confirmed instead of NotAuthorizedException.

Or if i understand something wrong just let me know. 
Thanks

P.S. Will be good to have delete all users functionality from user pool in aws console (this is needed at least for testing purposes)

![screen shot 2016-05-12 at 4 54 55 pm](https://cloud.githubusercontent.com/assets/17722579/15218855/f8d0a462-1861-11e6-844b-5a435df8d99f.png)

You can separate this to another ticket if you see this make sense to do.

**Comment by chetanme** [comment]
If I understand your use case correctly you want the users to be authenticated successfully even if they are unconfirmed. I will base the rest of my answer based on this, if it is incorrect let me know.

To to this, you should have a [PreSignUp trigger](http://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html#aws-lambda-triggers-pre-registration-example) which informs us to "autoConfirm" the users. This will allow you to authenticate without calling confirmSignUp API.

By default SignUp is a two step process to protect user pools against spam attacks where an attacker keeps on creating valid users in someone's user pool if he get's hold of his user pool id and client id. This is possible because SignUp is and unauthenticated API call. With an additional confirmation step we make sure that user is a legitimate user.

For the other requirement, we will take this as a feature request for batch operations on our console. Thanks for raising this concern.

**Comment by nuinisk** [comment]
Hi. 

Actually i want to provide confirmation ui for user signup, but just imagine if i process signup in device 1 without confirmation. Then i want to continue signup process in device 2 for the same user.

So my question is  - how can i get status of the user (is he already signed up?, signed up confirmed, signed up not confirmed, or did not signed up at all) to be able to show confirmation view.

So my assumption was if i will try to login with already signed up (not confirmed) user i will get status that this user signed up but not confirmed - instead of NotAuthorizedException.

Hope this will help you to understand my needs. 

Thank you.

**Comment by chetanme** [comment]
Our rationale to not reveal the information about the state of a user on authenticate is for better security. Returning an error that user exists and is unconfirmed essentially means that without any valid credentials we are telling the caller that user exists and is in some state. Some attacker who get holds of a user pool id and client id/secret can call authenticate API to enumerate users which exists in the system. This was the security concern which made us return a generic error.

Having said that, I understand your use case and see that it is not possible for developers to determine this right now. We will take this as a feature request too. Thank you.

**Comment by nuinisk** [comment]
Hi again.

The argument which you bring here is not valid. Of course you should validate user credentials before returning user status (So there is no any security related concern , at least not the one which you mention).

Also i want you to make clear - this functionality is essential for mobile devices, cause skipping the confirmation view (after signup) is pretty easy (navigating back/canceling the view, killing app, restarting phone, unexpected crash, ... ), and there is no other chance to reestablish user signup process, and user data will become completely useless (signup - "user already exists", signin - "Incorrect username or password"). 

So as you see without this the app will be less attractive and sometimes even disgusting.
So hope you will change your point of view and make this as an important issue (i would really appreciate if i ill have this in next release :)).

**Comment by chetanme** [comment]
I totally agree this is a very valid concern and we are considering this a important update. We will keep you posted when we change this behavior. Thank you again.

**Comment by nuinisk** [comment]
Thanks

**Comment by minbi** [comment]
Please re-open the issue if this still applies
