### ISSUE TITLE
Adding 'sessionKey' for AWSStaticCredentialsProvider init method

### ISSUE THREAD

**Issue by willard1218** [aws/aws-sdk-ios#392]
The [AWS SDK for Java](http://docs.aws.amazon.com/AWSSdkDocsJava/latest/DeveloperGuide/credentials.html) using **BasicAWSCredentials** to create a **BasicSessionCredentials** object.

Example 
```java
BasicSessionCredentials basic_session_creds = new BasicSessionCredentials(
   session_creds.getAccessKeyId(),
   session_creds.getSecretAccessKey(),
   session_creds.getSessionToken());

AmazonS3Client s3 = new AmazonS3Client(basic_session_creds);
```
But initialize method of **AWSStaticCredentialsProvider** haven't parameter *sessionKey*.

**Comment by yosuke-matsuda** [comment]
The static credentials provider should not take temporary credentials. Please remember they expire, and when they do, you need to get the new temporary credentials. Your credentials provider should retrieve them as needed from a remote server and cache them. The static credentials provider is not designed for this.

On the side note, `AWSCredentials` in the AWS Mobile SDK for iOS takes the session key. Thanks.

**Comment by willard1218** [comment]
Thanks for your explanation :)

**Comment by nipun0505** [comment]
@yosuke-matsuda I use this: 

AWSCredentials *newProvider = [[AWSCredentials alloc] initWithAccessKey:access_KEY_ID secretKey:secret_KEY_ID sessionKey:sessionToken expiration:nil];

AWSServiceConfiguration *config=[[AWSServiceConfiguration alloc]initWithRegion:AWSRegionUSWest2 credentialsProvider:newProvider];

But, AWSServiceConfiguration requires AWSStaticCredentialsProvider instead of AWSCredentials. Please help !
