### ISSUE TITLE
AWS Kinesis loops indefinetly when internet connection drops in the middle of a sync

### ISSUE THREAD

**Issue by joseandro** [aws/aws-sdk-ios#425]
App gets in an infinite loops when internet connection drops in the middle of a Kinesis sync.

**Tested iPad:**
iOS 9.3.2, iPad Air

**Preconditions:**
- Have some Kinesis logs stored in the device.

**Steps to reproduce:**
- Add a breakpoint to the Kinesis recorder, I used AWSAbstractKinesisRecorder.m#267
- Connect the app to the wifi network
- Start synching
- When execution halts the flow on your breakpoint, turn off the wifi network on your device
- Continue the execution flow

**Expected results:**
AWS Kinesis should stop syncing when the device goes offline

**Actual results:**
The app enters an infinite loop, it exhaustively tries to sync until the internet connection is back again. CPU usage skyrockets, the UI freezes and the app's UI turns unresponsive.

**Comment by joseandro** [comment]
This a sample of the console being hammered by logs:

`AWSiOSSDKv2 [Error] AWSKinesisRecorder.m line:147 | __109-[AWSKinesisRecorderHelper submitRecordsForStream:records:partitionKeys:putPartitionKeys:retryPartitionKeys:]_block_invoke | Error: [Error Domain=NSURLErrorDomain Code=-1009 "A conexão à Internet talvez esteja inativa." UserInfo={NSUnderlyingError=0x1581ac300 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorCodeKey=8, _kCFStreamErrorDomainKey=12}}, NSErrorFailingURLStringKey=https://kinesis.us-east-1.amazonaws.com/, NSErrorFailingURLKey=https://kinesis.us-east-1.amazonaws.com/, _kCFStreamErrorDomainKey=12, _kCFStreamErrorCodeKey=8, NSLocalizedDescription=A conexão à Internet talvez esteja inativa.}]`

`AWSiOSSDKv2 [Error] AWSURLSessionManager.m line:261 | -[AWSURLSessionManager URLSession:task:didCompleteWithError:] | Session task failed with error: Error Domain=NSURLErrorDomain Code=-1009 "A conexão à Internet talvez esteja inativa." UserInfo={NSUnderlyingError=0x1581c4950 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorCodeKey=8, _kCFStreamErrorDomainKey=12}}, NSErrorFailingURLStringKey=https://kinesis.us-east-1.amazonaws.com/, NSErrorFailingURLKey=https://kinesis.us-east-1.amazonaws.com/, _kCFStreamErrorDomainKey=12, _kCFStreamErrorCodeKey=8, NSLocalizedDescription=A conexão à Internet talvez esteja inativa.}`

You can translate the sentence "A conexão à Internet talvez esteja inativa" as "Your internet connection might be inactive".

**Comment by rohandubal** [comment]
Thank you for reporting this, we will have a look at this.

**Comment by AdrianaPineda** [comment]
@rohandubal 
Im also experiencing this issue. But it happens when I change the device time. Surprisingly it only happens if the time is ahead 10 or more days. I have the iOS 9 exception domains set up (as explain here: http://docs.aws.amazon.com/mobile/sdkforios/developerguide/ats.html)

`AWSiOSSDKv2 [Error] AWSKinesisRecorder.m line:147 | __109-[AWSKinesisRecorderHelper submitRecordsForStream:records:partitionKeys:putPartitionKeys:retryPartitionKeys:]_block_invoke | Error: [Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSURLErrorFailingURLPeerTrustErrorKey=<SecTrustRef: 0x12d86d320>, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, NSErrorPeerCertificateChainKey=<CFArray 0x12c7d3960 [0x1a002c150]>{type = immutable, count = 2, values = (
	0 : <cert(0x12d8b18f0) s: kinesis.us-east-1.amazonaws.com i: Symantec Class 3 Secure Server CA - G4>
	1 : <cert(0x12d8b1b40) s: Symantec Class 3 Secure Server CA - G4 i: VeriSign Class 3 Public Primary Certification Authority - G5>
)}, NSUnderlyingError=0x12c7d3b20 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrustRef: 0x12d86d320>, _kCFNetworkCFStreamSSLErrorOriginalValue=-9802, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, kCFStreamPropertySSLPeerCertificates=<CFArray 0x12c7d3960 [0x1a002c150]>{type = immutable, count = 2, values = (
	0 : <cert(0x12d8b18f0) s: kinesis.us-east-1.amazonaws.com i: Symantec Class 3 Secure Server CA - G4>
	1 : <cert(0x12d8b1b40) s: Symantec Class 3 Secure Server CA - G4 i: VeriSign Class 3 Public Primary Certification Authority - G5>
)}}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://kinesis.us-east-1.amazonaws.com/, NSErrorFailingURLStringKey=https://kinesis.us-east-1.amazonaws.com/, NSErrorClientCertificateStateKey=0}]`

**Comment by AdrianaPineda** [comment]
@rohandubal any updates on this?

**Comment by gapl** [comment]
Any updates?

**Comment by rohandubal** [comment]
Hello all, 

I am currently unable to reproduce this issue by setting break points and disabling my wifi connection on the device. @joseandro can you please provide more details into this? Does it only happen with iPad or happens with iPhone as well?

@AdrianaPineda can you please explain the use case where the date difference might be 10 days ahead? Does it happen on a normal operation when records are submitted on time?

Thanks,
Rohan

**Comment by joseandro** [comment]
@rohandubal it looks like this has been fixed a while ago by another commit.

**Comment by rohandubal** [comment]
HI @joseandro 

Were you using the older version of the SDK? Has the issue stopped appearing after updating to latest 2.4.x SDK?

Thanks,
Rohan

**Comment by AdrianaPineda** [comment]
Hi @rohandubal 

Im using version 2.3.6 which supports iOS 7. I can't user the latest cause Im still supporting iOS 7

Regarding the 10 day difference, we found out this issue while testing. I know this is an edge case for our users, but is curious that it happens just when changing the device time more than 10 days.

**Comment by rohandubal** [comment]
@AdrianaPineda you could use cocoapods with the latests 2.4.x SDKs for iOS 7 apps if required.
