### ISSUE TITLE
Issue with cognito internal credentials and logins caching 

### ISSUE THREAD

**Issue by nayna123** [aws/aws-sdk-ios#475]
We are using Cognito identity pool for the authentication purpose. Each user has one identity. For each user we are fetching open_id_token in logins, but that logins and internal credentials are getting cached and also being stored in key chain. We are clearing the key chain each time user logouts, but still whenever the other user logins it takes the credentials of the previous user. Is there any way we can prevent this?

**Comment by karthiksaligrama** [comment]
how are you clearing the keychain? Is it `clearKeychain` method in your credential provider?

**Comment by behrooziAWS** [comment]
It sounds like you are using a Cognito User Pool, when you sign out you need to sign out of both your identity pool (to invalidate the credentials) and your user pool (to invalidate the session so it is not used to get new credentials).  To sign out of user pools use `[user signOut]`.  To sign out of your identity pool use `[credentialsProvider clearKeychain]`

Note `[userPool clearAll]` isn't working currently due to this issue https://github.com/aws/aws-sdk-ios/issues/476

**Comment by karthiksaligrama** [comment]
Fixed with 2.4.10
