### ISSUE TITLE
Assertion failed: (buffer == NULL), function

### ISSUE THREAD

**Issue by iteamtech** [aws/aws-sdk-ios#504]
Assertion failed: (buffer == NULL), function -[MQTTEncoder encodeMessage:], file MQTTSDK/MQTTEncoder.m, line 123

**Comment by minbi** [comment]
@iteamtech Could you please provide some context?

What version of the SDK are you using?
What are the steps that lead to this failure?

**Comment by karthiksaligrama** [comment]
assuming resolved closing

**Comment by ostanik** [comment]
Hi, i'm having the same issue, i don't know if is the implementation... or some problem on the library. 
i'm using the 2.4.12 but on the version 2.4.10 also happens. 

i searched the code for more information but this issue is intermittent and i don't found a specific way to simulate that.

**Comment by ArisSarris** [comment]
I think the problem occurs when publishing from a different thread than the one used to connect. 
The `-[MQTTEncoder encodeMessage:]` function is not thread safe. 
The reason the issue does't appear often is because the publish event must fire at the same time the ping timer fires (which also publishes). If those two events fire from different threads, then the assertion will fail.
