### ISSUE TITLE
Crash in AWS SDK when we have send the wrong pool id

### ISSUE THREAD

**Issue by abdul-naveed** [aws/aws-sdk-ios#514]
More details explained here. http://stackoverflow.com/questions/40305165/application-crashes-when-logging-to-console?noredirect=1#comment67873037_40305165

**Comment by minbi** [comment]
Pasting for others with same problem
--

I found the fix Larme, Well i was sending the wrong pool id which wasn't containing "_". But AWS folks have not handled to log a warning or exception about this. My Bad i was doing it wrong. I downloaded thier source code and found the fix for the one. – Abdul Naveed
