### ISSUE TITLE
[AWSTask exception]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by sebamisc** [aws/aws-sdk-ios#590]
**Setup**

 - Amazon Mobile Hub to provision all services
 - AWS Cognito through Mobile Hub for Authentication / Identities
 - Facebook as Identity Provider activated
 - AWS DynamoDB activated in console but not yet used
 - AWS S3 activated in console but not yet used
 - All relevant libraries included through cocoapods
 - Integrated correct plist changes

> Sample Project downloaded from Amazon Mobile HUB works flawlessly (integrated frameworks)

**Working**

 - Succesfully able to compile project

**Problem / Not working**

 App crashes seconds after (successfull) launch as AWS Cognito tries to obtain `getId` with: 

    2017-02-13 16:25:06.220 dates[25642:544675] -[AWSTask exception]: unrecognized selector sent to instance 0x6180002656c0
    2017-02-13 16:25:06.222 dates[25642:544675] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[AWSTask exception]: unrecognized selector sent to instance 0x6180002656c0'
    *** First throw call stack:
    (
    	0   CoreFoundation                      0x000000010ff21d4b __exceptionPreprocess + 171
    	1   libobjc.A.dylib                     0x000000010f98321e objc_exception_throw + 48
    	2   CoreFoundation                      0x000000010ff91f04 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
    	3   CoreFoundation                      0x000000010fea7005 ___forwarding___ + 1013
    	4   CoreFoundation                      0x000000010fea6b88 _CF_forwarding_prep_0 + 120
    	5   dates                               0x000000010c43d917 __35-[AWSIdentityManager completeLogin]_block_invoke_2 + 263
    	6   libdispatch.dylib                   0x0000000112559978 _dispatch_call_block_and_release + 12
    	7   libdispatch.dylib                   0x00000001125830cd _dispatch_client_callout + 8
    	8   libdispatch.dylib                   0x00000001125638a4 _dispatch_main_queue_callback_4CF + 406
    	9   CoreFoundation                      0x000000010fee5e49 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
    	10  CoreFoundation                      0x000000010feab37d __CFRunLoopRun + 2205
    	11  CoreFoundation                      0x000000010feaa884 CFRunLoopRunSpecific + 420
    	12  GraphicsServices                    0x00000001136aea6f GSEventRunModal + 161
    	13  UIKit                               0x0000000110345c68 UIApplicationMain + 159
    	14  dates                               0x000000010c29b89f main + 111
    	15  libdyld.dylib                       0x00000001125cf68d start + 1
    	16  ???                                 0x0000000000000001 0x0 + 1
    )
    libc++abi.dylib: terminating with uncaught exception of type NSException

For me it seems to be an issue related to https://github.com/awslabs/aws-sdk-react-native/issues/41 (didnt find a corresponding swift issue) but `AWSTask.exception` does not longer exist.

Does someone know how to mitigate this issue, is it an AWS issue which we just have to wait out?

**Comment by azsolinsky** [comment]
Are you using the AWS HubHelper framework directly and other AWS dependencies through cocoapods?

**Comment by sebamisc** [comment]
I am using cocoapods for 99% of frameworks, the only static inclusion is the helper framework.

The code is (in my eyes) 1:1 identical (i dropped in the helper class, framework & plist.

I have 1 line in my appdelegate to return the awsdidfinish method without modification. The crash occurs within the call 'resumeSession' from the helper class.

**Comment by nathanws** [comment]
I'm having the same problem, with the exception that I am installing with Carthage instead of Cocoapods. I copied the code/framework from the MobileHub generated app into my app, following the directions included with the generated app.

I've noticed the "unrecognized selector" error is only happening after I log into the app. If I've never logged in, or if I log out (using `AWSIdentityManager.defaultIdentityManager().logout()`, the error does not occur.

If I enter an incorrect password for the User, the error does not occur.

Looking at the identity pool in Cognito, I can see that the identity is being created successfully.

In `AWSMobileClient.didFinishLaunching()` I commented out the `.resumeSession()` call, and the selector error is still occurring. So I don't think that's where the error is happening.

The only difference I can see between the generated MobileHub app and my app, is that the MobileHub app is compiled with Swift v2.3, and my app is Swift 3.0. Maybe it's an issue with the `AWSMobileHubHelper.framework` not being compatible with v3.0? I'm not sure that's it either, since the framework is written in Objective-C, but I don't know enough about how XCode compiles to say otherwise. I'm currently trying to convert my project to v2.3 just to see if this changes anything, I've tried everything else and this is my last resort.

The "unauthenticated access" error could be a logging level issue with your new app, it can be changed with `AWSLogger.default().logLevel = .whatever`.

**Comment by minbi** [comment]
Hi @sebamisc @nathanws ,

Swift 3 support has just been release, please download the MobileHub sample app again. Checking that it was generated with v0.10 template shown in any file's comments at the top.

**Comment by sebamisc** [comment]
With the new framework and updating all AWS related cocoapods to 2.5.1 it works :) Thank you!

**Comment by nathanws** [comment]
The new framework worked for me too. Good timing!

**Comment by azsolinsky** [comment]
This has been resolved with the latest release of the framework.

**Comment by GavinRooney** [comment]
I am having this same problem. 

I get 

'NSInvalidArgumentException', reason: '-[AWSTask exception]: unrecognized selector sent to instance 

shortly after trying to setup aws client

[[AWSMobileClient sharedInstance] didFinishLaunching:application withOptions:launchOptions]

- AWSCognitoIdentityProvider (2.5.1):
    - AWSCore (= 2.5.1)
  - AWSCore (2.5.1)

I am using AWSMobileHubHelper.framework which I just downloaded today. I am only using the signup/login configuration.

**Comment by GavinRooney** [comment]
When I remove them from pods and use the the 2 frameworks (AWSCognitoIdentityProvider and  AWSCore ) that come with the sample code from AWSMobileHub it works fine. So I will continue with the embedded frameworks for now and maybe come back to cocoapods some time down the line to check if it is back working. I will leave sample test project up for awhile in case anyone can check it out and find what I am doing wrong

**Comment by swl367** [comment]
I'm having the same issue as @GavinRooney when using the following frameworks on v2.5.1

- AWSAPIGateway
- AWSCore
- AWSPinpoint
- AWSS3
- AWSSNS

I'm using embedded frameworks for all of these (no cocoapods), but I get the unrecognized selector error.

**Comment by kjoneandrei** [comment]
same issue as  @GavinRooney  ... using all the AWS iOS SDK Pods - v.2.5.6 + MobileHubHelper as a static Framework taken from the demo project downloaded today. 

Using the Frameworks (no Pods) from the static project though works without a problem. Any idea why CocoaPods added Frameworks cause problems?

**Comment by ChrisBGriffith** [comment]
Also experiencing this when using Cocoapods. Anyone identified the underlying issue?
