### ISSUE TITLE
AWS IOT Shadow timer crash

### ISSUE THREAD

**Issue by ramki982** [aws/aws-sdk-ios#640]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWS IOT
* In what version of SDK are you facing the problem?
2.5.3
* Is the issue limited to Simulators / Actual Devices?
Both
* Can your problem be resolved if you bump to a higher version of SDK?
No
* Is this problem related to specific iOS version?
No
* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
Cocoapods
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

shadowOperationTimeoutOnTimer method in AWSIotDataManager is not checking if the shadow was unregistered when it is fired

The above method (shadowOperationTimeoutOnTimer) retrieves the shadow from "shadows dictionary". But there is chance that the shadows dictionary no longer contains a shadow object if unregister shadow gets called asynchronously. In the above scenario - the shadow object from the dictionary will return a nil object causing shadow.callback (line number 672) to crash.

See the repro screenshot from the Xcode. Ideally the unregister should invalidate the timer and also the shadowOperationTimeoutOnTimer method should ensure shadow is not nil 
![screen_shot_2017-04-17_at_10 44 22_am](https://cloud.githubusercontent.com/assets/353611/25114757/ac077a88-241e-11e7-9680-ed5bb94c24e6.png)

**Comment by ramki982** [comment]
@fengsongAWS - can you help with the above crash?

**Comment by minbi** [comment]
Version 2.5.5 has been released

**Comment by Banner2404** [comment]
Seems like this issue still occurs in SDK 2.29.1. Similar to what @ramki982 pointed out above, we get occasional **EXC_BAD_ACCESS** crashes in 
`-[AWSIoTDataManager handleMessagesForShadow:operation:status:payload:] + 1464 (AWSIoTDataManager.m:1008)
`
Though I was not able to reliably reproduce this issue. Seems like it happens when client unsubscribes from shadow and disconnects from one thread (main) and shadow event is handled in another thread (background)

<img width="1018" alt="Screenshot 2023-02-02 at 11 40 14" src="https://user-images.githubusercontent.com/17294609/216303402-31cdac76-bd40-4fbb-aab7-654fb55bd537.png">


Attaching crash log 
[aws_iot_crash.txt](https://github.com/aws-amplify/aws-sdk-ios/files/10567923/aws_iot_crash.txt)
