### ISSUE TITLE
Error using AWS Frameworks and Cocoapods

### ISSUE THREAD

**Issue by David-FR** [aws/aws-sdk-ios#653]
I'm trying to integrate the AWS SDK with my app, currently I'm only using Cognito and DynamoDB. My app also uses Cocoapods ( pod 'GoogleMaps', pod 'GooglePlaces', pod 'SwiftyJSON', '3.0.0', etc.) I can integrate with no problems if I don't use any pod. However if I install any pod and build the app I get the following errors: 

![image](https://cloud.githubusercontent.com/assets/18079431/25638314/984cf236-2f4d-11e7-91ca-a4937d1a133b.png)
![image](https://cloud.githubusercontent.com/assets/18079431/25638318/9ff08f7a-2f4d-11e7-831e-7044295bbc6c.png)
![image](https://cloud.githubusercontent.com/assets/18079431/25638293/869505e2-2f4d-11e7-8db4-9594762c27bd.png)

This errors happen even if use the sample app provided in MobileHub (Again, only happens if I use and install any pod)

Any ideas?

**Comment by rohandubal** [comment]
Hello, the above issue is related to Mobile Hub Helper which belongs to this repository:
https://github.com/aws/aws-mobilehub-helper-ios

 Could you please open this issue there?

It is most likely due to -ObjC flag added by cocoapods. You need to use the -force_load flag as specified in Mobile Hub instructions.

Thanks,
Rohan
