### ISSUE TITLE
SecretHash calculation username = nil crash

### ISSUE THREAD

**Issue by mosn** [aws/aws-sdk-ios#724]
* What service are you using?
AWSCognitoIdentity
* In what version of SDK are you facing the problem?
Latest
* Is the issue limited to Simulators / Actual Devices?
Both
* Can your problem be resolved if you bump to a higher version of SDK?
No
* Is this problem related to specific iOS version?
No
* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
When starting a custom authentication for the first time on a device that has no username, `addSecretHashDeviceKeyAndUsername:` declared in `AWSCognitoIdentityUser:762` will try to set `self.username` for key `USERNAME` but since the there are no username yet, the app will crash. 

Possible solution would be to look into passed parameter `authParameters`instead of `self.username` to find the username and use that for the hash calculation.  

Any alternative solutions ? because my solution requires modification to SDK.

**Comment by behrooziAWS** [comment]
Do you have the username up front?  Because you could call [this method](http://docs.aws.amazon.com/AWSiOSSDK/latest/Classes/AWSCognitoIdentityUserPool.html#//api/name/getUser:) with the username to set it before calling getSession.  We can investigate falling back to the authParameters to extract the username for a future release.

**Comment by rohandubal** [comment]
Fixed with 2.6.2.
