### ISSUE TITLE
Resend Email Verification Link  for Cognito UserPool Sign up

### ISSUE THREAD

**Issue by sourabhzynq** [aws/aws-sdk-ios#793]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWS Cognito
* In what version of SDK are you facing the problem?
2.4.12
* Is the issue limited to Simulators / Actual Devices?
NO
* Can your problem be resolved if you bump to a higher version of SDK?
NO
* Is this problem related to specific iOS version?
NO
* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?
CocoaPods
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

Hi, 

Is there any method to resend the  **Email verification link** during Sign Up with AWS Cognito UserPool? As I can see Cognito has a provision for Resend Confirmation Code to Phone or Email, but I could not find any such method available to resend verification **link** in any of the documentation available.

**Comment by pothunoorisk** [comment]
While working around I found that the same method that sends the confirmation code can be user to resend verification link!

**Comment by sourabhzynq** [comment]
While working around I found that the same method that sends the confirmation code gives me a new verification link! Assuming this is correct, we can close this issue(!).

**Comment by alionthego** [comment]
can you please let me know which method that is?  I'm having issues getting a new verification link.  thanks

**Comment by sourabhzynq** [comment]
Same method that we use to resend the confirmation code i.e. resendConfirmationCode. This sends a code via email - not the link.

**Comment by alionthego** [comment]
I see.  Sorry, I misunderstood.  I am trying to have the verification link sent again in case the user did not receive it or it has expired.  Not the code.

**Comment by sourabhzynq** [comment]
Try the same method. It will send a link to email. I incorrectly wrote the "code" in above answer, corrected it.

**Comment by alionthego** [comment]
I'm using the swift SDK to create a new user.  So I can't use the same method.  The best I've found so far is to use the updateAttributes method with the new email.  That works fine but instead of sending a verification link like I get when the user signs up, this time it sends a code for some reason and I don't think there is anyway to get around that and send another link.  I don't want to register the user again because it will be rejected (user already exists) and also I have triggers which will be fired again.

**Comment by recreational-snacker** [comment]
Hi,
I'm getting:
{
  "code": 400,
  "message": "Can't resend confirmation code for this user (Service: AWSCognitoIdentityProvider; Status Code: 400; Error Code: NotAuthorizedException; Request ID: 71383829-65ac-11e8-b265-a701b68c006a)"
}
When trying resendConfirmationCode in Cognito (Java SDK version 1.11.279). Can anyone help me shed light on this?

**Comment by Yaswanth-C** [comment]
HI @alionthego  Thanks for your workaround solution , did you checked with AWS cognito team for any alternate ?

**Comment by itzAsim** [comment]
There is an in-built methods for same from Cognito- 
First get a user from AWS Cognito UserPool
user = pool?.getUser(email!)
user?.resendConfirmationCode().continueWith(block: {[weak self] (task: AWSTask) -> AnyObject? in
})

**Comment by cylidGBS** [comment]
please can any one provide source code of resend confirmation code in cognito c#

**Comment by tehcooky** [comment]
my problem is this will not happen if a user is confirmed. Lets say for example i change an email, it doesnt unconfirm me, but i now can no longer resend the code because it says my user is already confirmed. And there doesnt seem to be a way to unconfirm a user? maybe if i force change password? im not sure
