### ISSUE TITLE
How to use the AWSDynamodb service for beginner?

### ISSUE THREAD

**Issue by DavidPhysics** [aws/aws-sdk-ios#794]
### How to use the AWSDynamodb service for beginner?

* I create the iOS app with the AWSCognito and the AWSDynamodb. 
   My Xcode version is 8.3.3 (8E3004b).
   My cocoapods version is 1.3.1. 

* My problems: **Dynamodb service.**
  I add the Dynamodb service in my iOS project and follow the dynamodb essay of the AWS developer guide for iOS, but it doesn't work in my projects. I also add the save code of the AWS dynamodb service. It also doesn't 

**Could tell me the dynamodb guide for beginner?**

* My process:
Step1: Create the new sub-class in my project. 
Step2: Add the example cod of the AWS developer guide for iOS in my new sub-class header files. 
Step3: The code show error messages about '#import "Book.h"'.
Step4: Command-B 
-----
**My sub-class header file:**
-----
#import <AWSDynamoDB/AWSDynamoDB.h>
#import "Book.h"

@interface Book : AWSDynamoDBObjectModel <AWSDynamoDBModeling>

@property (nonatomic, strong) NSString *Title;
@property (nonatomic, strong) NSString *Author;
@property (nonatomic, strong) NSNumber *Price;
@property (nonatomic, strong) NSString *ISBN;

@end

@implementation Book

+ (NSString *)dynamoDBTableName {
    return @"Books";
}

+ (NSString *)hashKeyAttribute {
    return @"ISBN";
}

@end

**Comment by kredden** [comment]
Since you are a beginner I'd start by using AWS Mobile Hub:

https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html

And the DynamoDB specific section:

https://docs.aws.amazon.com/aws-mobile/latest/developerguide/add-aws-mobile-nosql-database.html.

Also, posting issues to GitHub is normally meant for that, issues.  If you are looking for more help on how to do something then you should be posting to the AWS Forums or StackOverflow.

Regards,
Kevin
