### ISSUE TITLE
The product name of Google is wrong on Google Login Screen

### ISSUE THREAD

**Issue by huyttn123** [aws/aws-sdk-ios#818]
HI
I use AWS SDK Auth to connect with Google with my product name: <my_product_namne>. But on the login screen of Google, it always show "amazoncognito.com" instead of <my_product_namne>
You can see it on image below

<img width="375" alt="35135643-1bf110ae-fd11-11e7-8f9e-7d516b0435b6" src="https://user-images.githubusercontent.com/6301093/35263863-18e4675a-004d-11e8-8467-528b681b5494.png">

Please help me about this issue. This is issue of SDK or I need check and config more param ?

**Comment by huyttn123** [comment]
Anyone please help me about this. Thanks

**Comment by huyttn123** [comment]
Anyone please help me about this. Thanks

**Comment by kvasukib** [comment]
Hello @huyttn123,

Sorry for the inconvenience caused. The code in the repository "amazon-cognito-ios" is no longer supported. The Google SignIn functionality is currently offered by the Amazon Cognito Auth library. This provides you the sign-in in a web/hosted UI rather than a native UI.

https://github.com/awslabs/aws-sdk-ios-samples/tree/master/CognitoAuth-Sample
