### ISSUE TITLE
Uploading with Multipart is crashing because low memory on big files.

### ISSUE THREAD

**Issue by David-Madpixel** [aws/aws-sdk-ios#914]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?

AWS iOS SDK (AWSS3TransferUtility)

* In what version of SDK are you facing the problem?

2.6.16

* Is the issue limited to Simulators / Actual Devices?

Device (I couldn't test on Simulator)

* Can your problem be resolved if you bump to a higher version of SDK?

No

* Is this problem related to specific iOS version?

Not sure

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks?

Prebuilt.

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

Using standard code from documentation and uploadFileUsingMultiPart is causing crash because low memory. 

uploadFileUsingMultiPart is loading full file on memory while uploading, so with big size (2GB) files is causing a crash (Terminated due to memory issue)

```
AWSS3TransferUtilityMultiPartUploadExpression *expression = [[AWSS3TransferUtilityMultiPartUploadExpression alloc] init];
    
    expression.progressBlock = progressHandler;
    
    AWSS3TransferUtilityMultiPartUploadCompletionHandlerBlock completionHandler = ^(AWSS3TransferUtilityMultiPartUploadTask *task, NSError *error) {
        dispatch_async(dispatch_get_main_queue(), ^{
            
        });
    };
    
    AWSS3TransferUtility *transferUtility = [AWSS3TransferUtility defaultS3TransferUtility];
    
    [[transferUtility uploadFileUsingMultiPart:file
                                        bucket:bucket
                                          key:[NSString stringWithFormat:@"%@/%@",directory,[file lastPathComponent]]
                                  contentType:@"application/zip"
                                   expression:expression
                            completionHandler:completionHandler]
     continueWithExecutor:[AWSExecutor mainThreadExecutor]
     withBlock:^id(AWSTask *task)
     {
         return nil;
     }];
```

**Comment by cbommas** [comment]
hello @David-Madpixel 

Sorry to hear that you are running into issues. I will look into this and get back to you.

**Comment by cbommas** [comment]
hello @David-Madpixel 

I was able to reproduce the issue on my side. The problem was that the Multipart logic has a fast loop for chunking the files, which reads the input file and breaks them into smaller chunks. In this tight loop, the contents of the file are read and used to create the part-files. While there was no memory leak, the code was asking for memory to be allocated and deallocated in an aggressive fashion, which can cause iOS to terminate the process due to memory pressure. I changed the  logic to only create the file chunks needed, based on max concurrency, and create the remaining chunks in a just-in-time fashion when the previous chunks finished uploading.

With this updated logic, I was able to successfully upload a 3GB file using Multipart. This fix will be available in the next rev of the SDK.

**Comment by minbi** [comment]
Hi @David-Madpixel ,

We have released version 2.6.18 of the SDK. Please see if the issue is resolved.

**Comment by David-Madpixel** [comment]
Hello. 

I can confirm the issue is resolved with last version

Thank you

**Comment by cbommas** [comment]
Thank you for confirming @David-Madpixel
