### ISSUE TITLE
AWSCognitoIdentityPasswordAuthentication.didCompleteStepWithError called, but identityPool?.currentUser()?.isSignedIn still returns false for another second or so

### ISSUE THREAD

**Issue by michaeleconomy** [aws/aws-sdk-ios#957]
Hi,

I'm using AWSCognitoIdentityPasswordAuthentication and AWSCognitoIdentityInteractiveAuthenticationDelegate to add cognito authentication to my ios app.  For the most part this is working.   This was particularly annoying and weird so i'm reporting it.

So after i put in my username and password, hit login, do:
let authDetails = AWSCognitoIdentityPasswordAuthenticationDetails(username: emailField.text ?? "", password: passwordField.text ?? "")
        self.passwordAuthenticationCompletion?.set(result: authDetails)

AWSCognitoIdentityPasswordAuthentication.didCompleteStepWithError is called.  Great! i'm signed in right?  Wrong!  - identityPool?.currentUser()?.isSignedIn still returns false for another second or so   i tried doing some sort of identityPool?.currentUser()?.getDetails().continueOnSuccessWith  but thats not working.

here's my project for additional context:
https://github.com/michaeleconomy/sketchaphone

**Comment by rohandubal** [comment]
I think the confusion stems from the method name. `didCompelteStepWithError` is called with an error object indicating there was an error signing in the user and that the username and password needs to be requested again. Thats why the isSignedIn correctly returns false.

**Comment by michaeleconomy** [comment]
Nope, thats not the problem.   I see how people could make that mistake however.

**Comment by behrooziAWS** [comment]
`didCompletePasswordAuthenticationStepWithError` doesn't mean the authentication has completed, it just means the current step has completed or errored out, there may not be tokens yet.  `getSession`, like most of the apis is an asynchronous task, there is no guarantee that it has completed unless you call `continueWith` or `continueWithSuccess` on it. `getSession` which is called by most apis, including `getDetails` will return an error on failure, so there should be no need to call `isSignedIn` unless you are trying to determine before you even show a screen whether a user is signed in.  For more details on how to use continueWith/continueWithSuccess look here: https://github.com/BoltsFramework/Bolts-Swift

**Comment by kiwi-26** [comment]
I'm encountering the same problem.

I use Cognito federated identity with userpool.
Before a user signs in, the user have cognitoIdentityId with unauthenticated role, and after signs in, I want user to use identityId with authenticated role.

So I wrote some code like
```
func didStep(_ error: Error) {
    self.credentialsProvider.setIdentityProviderManagerOnce(self.pool)
    self.credentialsProvider.getIdentityId().continueWithBlock { (task) -> AnyObject? in 
        // some task with cognito ID
    }
}
```
but I can't getIdentityId correctly because userpool object (or currentUser object) is not updated with signed in tokens.

How can I determine updated userpool or current user status?

**Comment by behrooziAWS** [comment]
@michaeleconomy yeah that is the correct pattern.  FWIW, it should also work with `getDetails().continueOnSuccessWith` since it is doing exactly that: https://github.com/aws/aws-sdk-ios/blob/master/AWSCognitoIdentityProvider/AWSCognitoIdentityUser.m#L148

@kiwi-26  To support unauth and auth users, there are a couple ways to doing it, but I wouldn't do it in the didStep method.  Instead maybe you can wait to instantiate your credentials provider until after you've decided whether the user is going to be authenticated or not.  If unauth, don't pass the user pool to the credentials provider, if auth, do pass it.  You can use `isSignedIn` to determine whether they have previously authenticated.  Be sure to call clearCredentials on the credentials provider if you are switching from auth to unauth or vice versa so you don't have any stale credentials.  The credentials provider will automatically call getSession on the current user when it first needs to get credentials to access AWS so there is no need to proactively call anything unless you want to.

**Comment by michaeleconomy** [comment]
Ok ".getSession().continue" is not working,  instead it seems to be firing AWSCognitoIdentityInteractiveAuthenticationDelegate.startPasswordAuthentication()
 and never calling the block.

What i was doing instead, that seems to work is:

 func waitForSignIn(_ callback: @escaping () -> Void) {
        if (identityPool?.currentUser()?.isSignedIn) {
            callback()
            return
        }
        NSLog("not signed in, waiting another second")
        DispatchQueue.main.asyncAfter(deadline: .now() + .seconds(1), execute: {
            self.waitForSignIn(callback)
        })
}

This is kind of gross, but works.

**Comment by harsheno8** [comment]
I am facing the same issue. Using dispatch as mentioned by @michaeleconomy I was able to get it running. What am I doing workng here?
```
DispatchQueue.main.asyncAfter(deadline: .now() + .seconds(1), execute: {
self.waitForSignIn(callback)
})
}
```
