### ISSUE TITLE
What AWSCognitoAuthErrorDomain actually means?

### ISSUE THREAD

**Issue by fernnando** [aws/aws-sdk-ios#966]
* What service are you using?
Amazong Cognito

Im getting this error (com.amazon.cognito.AWSCognitoAuthErrorDomain) when i try to login for the second time(after a successful logout), but cant find it on any AWS documentation.

**Comment by kvasukib** [comment]
Thank you @fernnando for reporting to us. Sorry for the inconvenience caused. Can you post the exception message and complete stack trace and a code snippet?

**Comment by kwallace-abvio** [comment]
I use the iOS SDK.  I use -[AWSCognitoAuth getSession:completion:] to sign in using Facebook and -[AWSCognitoAuth signOut:completion:]  to sign out.  If I install my app from scratch, sign in with Facebook works.  Then if I sign out and attempt to sign in again, -[AWSCognitoAuth getSession:completion:] returns with the error AWSCognitoAuthErrorDomain, AWSCognitoAuthClientErrorLoadingPageFailed.  Basically the page flashes in the Safari View Controller and then disappears.  Previously instead of simply not being able to sign in as a different user, I now can't even sign in  again as the same user.  The only way I can sign in again is to either visit the iOS Settings app and remove all cookies and data from Safari or delete and reinstall my iOS app.  I need my users to be able to login again.  How can I fix or address this problem?  Repeated login ought to simply work.

No stack track or code snipped is needed in my opinion.  Just sign in and sign out using AWSCognitoAuth  and then see if you can sign in again with the same code.
